# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:            pretty
#relative_permalinks:  true

# Setup
title:                "Bref News"
tagline:              "L'actualité synthétisée"
description:          "<a href=\"https://twitter.com/BrefNews\" target=\"_blank\">Bref News</a> va à l'essentiel&nbsp;: des titres synthétisés avec soin pour une lecture adaptée aux smartphones."
url:                  "http://bref.news"
baseurl:              ""
paginate:             1

# About/contact
author:
  name:               "Bref News"
  url:                "http://bref.news"
  email:              "contact@bref.news"

# Custom vars
twitter:              "https://twitter.com/BrefNews"

prev_article:         "Article précédent"
next_article:         "Article suivant"
home:                 "Accueil"
twitter:              "Twitter"
